# Copyright (c) 2022-2025, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

seed: 42


# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
models:
  separate: True
  policy:  # see gaussian_model parameters
    class: GaussianMixin
    clip_actions: False
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: -4.0
    network:
      - name: net
        input: OBSERVATIONS
        layers: [1024, 512, 512]
        activations: elu
    output: ACTIONS
    output_activation: tanh  # Bound actions to [-1, 1]
    output_scale: 1.0
    # intialization
    zero_init_last_layer: True
    initialization: orthogonal_
    initialization_kwargs:
      gain: 0.3
  value:
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: OBSERVATIONS
        layers: [1024, 512, 512]
        activations: elu
    output: ONE


# Rollout memory
# https://skrl.readthedocs.io/en/latest/api/memories/random.html
memory:
  class: RandomMemory
  memory_size: -1  # automatically determined (same as agent:rollouts)


# PPO agent configuration (field names are from PPO_DEFAULT_CONFIG)
# https://skrl.readthedocs.io/en/latest/api/agents/ppo.html
agent:
  class: PPO
  rollouts: 300
  learning_epochs: 20
  mini_batches: 5
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: [2.5e-04, 1.0e-03]  # [policy (actor), value (critic)] learning rates
  # learning_rate_scheduler: KLAdaptiveLR
  # learning_rate_scheduler_kwargs:
  #   kl_threshold: 0.016
  # state_preprocessor: RunningStandardScaler
  # state_preprocessor_kwargs: null
  value_preprocessor: RunningStandardScaler
  value_preprocessor_kwargs: null
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: True
  entropy_loss_scale: 0.00
  value_loss_scale: 1.0
  kl_threshold: 0.0
  rewards_shaper_scale: 1.0
  time_limit_bootstrap: False
  # logging and checkpoint
  experiment:
    directory: "sg_gr00t_rl"
    experiment_name: ""
    write_interval: 300
    checkpoint_interval: 2000
    wandb: True
    wandb_kwargs:
      project: MR-GR00T
      entity: star-lab-gt


# Sequential trainer
# https://skrl.readthedocs.io/en/latest/api/trainers/sequential.html
trainer:
  class: SequentialTrainer
  timesteps: 100000
  environment_info: log